#!/bin/bash
# mount GCS bucket as directory
gcsfuse mytransfer-files uploadedfiles/
# run program under authbind
authbind Mytransfer/Mytransfer
# unmount bucket
fusermount -u uploadedfiles/
# put server into TERMINATED state for later deletion by the autoscaler
sudo shutdown -h now
